name = "dyeli"
main = "worker/index.mjs"
compatibility_date = "2022-10-19"
# workers_dev = true
minify = true
routes = [
  # Domain where this is hosted e.g. sh0.rt
  { pattern = "sh0.rt", custom_domain = true },
  { pattern = "www.sh0.rt", custom_domain = true }
]

[vars]
  # Where non-valid URLs should go
  DEFAULT_REDIRECT = "https://example.com"
  # URL for favicon
  FAVICON_URL = "https://svg.siq.li/?width=384&height=384&bg_color=D4632DF3&text=*"
